# AUTHORITY: verbatim copy of the actuator patch functions from
#   code/train_and_test/ppo/src/env/modified_env.py (lines 1-193).
# Do NOT edit this file independently — pull changes from the source above.
# Kept in sync with commit that introduced the sys-ID actuator model.

import collections
import numpy as np
from numba import njit
from f110_gym.envs import base_classes
from f110_gym.envs.dynamic_models import vehicle_dynamics_st


@njit(cache=True)
def better_pid(speed, delayed_delta_cmd, current_speed, current_steer,
               current_accel, current_delta_dot, dt, min_sv, max_sv,
               tau_v, tau_a, a_max, tau_delta, tau_delta_dot,
               delta_th, steer_gamma):
    """
    Controller for delayed speed/steer commands -> acceleration/steering velocity.
    """

    # steering
    delayed_delta_cmd_sq = delayed_delta_cmd * delayed_delta_cmd
    delayed_delta_cmd_cb = delayed_delta_cmd_sq * delayed_delta_cmd
    delta_th_sq = delta_th * delta_th

    delta_target = delayed_delta_cmd_cb / ((delayed_delta_cmd_sq + delta_th_sq)*(1 + steer_gamma * delayed_delta_cmd_sq))
    delta_dot_des = (delta_target - current_steer) / tau_delta
    delta_ddot = (delta_dot_des - current_delta_dot) / tau_delta_dot
    sv = current_delta_dot + dt * delta_ddot
    if sv > max_sv:
        sv = max_sv
    elif sv < min_sv:
        sv = min_sv

    # acceleration
    a_des = (speed - current_speed) / tau_v
    if a_des > a_max:
        a_des = a_max
    elif a_des < -a_max:
        a_des = -a_max

    # check that the acceleration is not changing too fast
    accl = current_accel + dt * ((a_des - current_accel) / tau_a)
    if accl > a_max:
        accl = a_max
    elif accl < -a_max:
        accl = -a_max

    return accl, sv


def _delay_steps(params, time_step, delay_key, default=0.0):
    delay = float(params.get(delay_key, default))
    return max(0, int(np.ceil(delay / time_step)))


def _reset_actuator_models(car):
    steer_delay_default = float(getattr(car, 'steer_buffer_size', 1)) * car.time_step

    car.accel = 0.0
    car.v_cmd_buffer = collections.deque(
        [0.0] * _delay_steps(car.params, car.time_step, 't_vd'),
        maxlen=_delay_steps(car.params, car.time_step, 't_vd'),
    )
    car.delta_dot = 0.0
    car.delta_cmd_buffer = collections.deque(
        [0.0] * _delay_steps(car.params, car.time_step, 't_sd', steer_delay_default),
        maxlen=_delay_steps(car.params, car.time_step, 't_sd', steer_delay_default),
    )


def _delayed_command(car, buffer_name, cmd):
    if not hasattr(car, buffer_name):
        _reset_actuator_models(car)

    buffer = getattr(car, buffer_name)
    if buffer.maxlen == 0:
        # Defensive: if t_vd/t_sd are set to 0 in config, the buffer is empty → pass through.
        return float(cmd)
    delayed_cmd = buffer[0]
    buffer.append(float(cmd))

    return delayed_cmd


def _delayed_speed_cmd(car, speed_cmd):
    return _delayed_command(car, 'v_cmd_buffer', speed_cmd)


def _delayed_steer_cmd(car, steer_cmd):
    return _delayed_command(car, 'delta_cmd_buffer', steer_cmd)


_ORIGINAL_RACECAR_RESET = base_classes.RaceCar.reset
_ORIGINAL_RACECAR_UPDATE_PARAMS = base_classes.RaceCar.update_params


def _racecar_reset_modified(self, pose):
    _ORIGINAL_RACECAR_RESET(self, pose)
    _reset_actuator_models(self)


def _racecar_update_params_modified(self, params):
    _ORIGINAL_RACECAR_UPDATE_PARAMS(self, params)
    _reset_actuator_models(self)


def _racecar_update_pose_modified(self, raw_steer, vel):
    delayed_vel = _delayed_speed_cmd(self, vel)
    delayed_steer = _delayed_steer_cmd(self, raw_steer)
    accl, sv = better_pid(
        delayed_vel,
        delayed_steer,
        self.state[3],
        self.state[2],
        self.accel,
        self.delta_dot,
        self.time_step,
        self.params['sv_min'],
        self.params['sv_max'],
        max(float(self.params.get('tau_v', self.time_step)), 1e-9),
        max(float(self.params.get('tau_a', self.time_step)), 1e-9),
        self.params['a_max'],
        max(float(self.params['tau_delta']), 1e-9),
        max(float(self.params['tau_delta_dot']), 1e-9),
        max(float(self.params['delta_th']), 1e-9),
        float(self.params['steer_gamma']),
    )
    self.accel = accl
    self.delta_dot = sv

    if self.integrator is base_classes.Integrator.RK4:
        k1 = vehicle_dynamics_st(
            self.state, np.array([sv, accl]), self.params['mu'], self.params['C_Sf'],
            self.params['C_Sr'], self.params['lf'], self.params['lr'], self.params['h'],
            self.params['m'], self.params['I'], self.params['s_min'], self.params['s_max'],
            self.params['sv_min'], self.params['sv_max'], self.params['v_switch'],
            self.params['a_max'], self.params['v_min'], self.params['v_max'])

        k2_state = self.state + self.time_step * (k1 / 2)
        k2 = vehicle_dynamics_st(
            k2_state, np.array([sv, accl]), self.params['mu'], self.params['C_Sf'],
            self.params['C_Sr'], self.params['lf'], self.params['lr'], self.params['h'],
            self.params['m'], self.params['I'], self.params['s_min'], self.params['s_max'],
            self.params['sv_min'], self.params['sv_max'], self.params['v_switch'],
            self.params['a_max'], self.params['v_min'], self.params['v_max'])

        k3_state = self.state + self.time_step * (k2 / 2)
        k3 = vehicle_dynamics_st(
            k3_state, np.array([sv, accl]), self.params['mu'], self.params['C_Sf'],
            self.params['C_Sr'], self.params['lf'], self.params['lr'], self.params['h'],
            self.params['m'], self.params['I'], self.params['s_min'], self.params['s_max'],
            self.params['sv_min'], self.params['sv_max'], self.params['v_switch'],
            self.params['a_max'], self.params['v_min'], self.params['v_max'])

        k4_state = self.state + self.time_step * k3
        k4 = vehicle_dynamics_st(
            k4_state, np.array([sv, accl]), self.params['mu'], self.params['C_Sf'],
            self.params['C_Sr'], self.params['lf'], self.params['lr'], self.params['h'],
            self.params['m'], self.params['I'], self.params['s_min'], self.params['s_max'],
            self.params['sv_min'], self.params['sv_max'], self.params['v_switch'],
            self.params['a_max'], self.params['v_min'], self.params['v_max'])

        self.state = self.state + self.time_step * (1 / 6) * (k1 + 2 * k2 + 2 * k3 + k4)
    elif self.integrator is base_classes.Integrator.Euler:
        f = vehicle_dynamics_st(
            self.state, np.array([sv, accl]), self.params['mu'], self.params['C_Sf'],
            self.params['C_Sr'], self.params['lf'], self.params['lr'], self.params['h'],
            self.params['m'], self.params['I'], self.params['s_min'], self.params['s_max'],
            self.params['sv_min'], self.params['sv_max'], self.params['v_switch'],
            self.params['a_max'], self.params['v_min'], self.params['v_max'])
        self.state = self.state + self.time_step * f
    else:
        raise SyntaxError(f"Invalid Integrator Specified. Provided {self.integrator.name}. Please choose RK4 or Euler")

    if self.state[4] > 2 * np.pi:
        self.state[4] = self.state[4] - 2 * np.pi
    elif self.state[4] < 0:
        self.state[4] = self.state[4] + 2 * np.pi

    scan_x = self.state[0] + self.lidar_dist * np.cos(self.state[4])
    scan_y = self.state[1] + self.lidar_dist * np.sin(self.state[4])
    scan_pose = np.array([scan_x, scan_y, self.state[4]])
    scan_simulator = base_classes.RaceCar.scan_simulator
    if scan_simulator is None:
        raise RuntimeError("RaceCar scan simulator is not initialized.")
    return scan_simulator.scan(scan_pose, self.scan_rng)


def apply_custom_actuator_patch():
    base_classes.RaceCar.reset = _racecar_reset_modified
    base_classes.RaceCar.update_params = _racecar_update_params_modified
    base_classes.RaceCar.update_pose = _racecar_update_pose_modified
